# Generated by Django 3.0.8 on 2020-10-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='pics')),
                ('dateStart', models.DateTimeField()),
                ('date1', models.DateTimeField(auto_now_add=True)),
                ('dateFinish', models.DateTimeField()),
                ('address', models.CharField(max_length=256)),
            ],
        ),
    ]
