# Generated by Django 3.0.8 on 2020-11-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ImageField(upload_to='pics')),
                ('header_bg', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
