# Generated by Django 3.0.8 on 2020-11-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0002_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='header_bg',
        ),
        migrations.AddField(
            model_name='picture',
            name='desc',
            field=models.TextField(default=True),
        ),
    ]
