# Generated by Django 3.0.8 on 2020-11-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0003_auto_20201107_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otherpicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_bg', models.ImageField(upload_to='pics')),
                ('logo', models.ImageField(upload_to='pics')),
                ('about', models.ImageField(upload_to='pics')),
                ('about_video', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
