# Generated by Django 3.0.8 on 2020-11-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0007_bwsmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bwsmembership',
            name='Age',
            field=models.CharField(choices=[('18-24', '18-24'), ('25-29', '25-29'), ('30-34', '30-34'), ('35-39', '35-39'), ('40-49', '40-49'), ('49 and older', '49 and older')], max_length=200),
        ),
    ]
