# Generated by Django 3.0.8 on 2020-11-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0008_auto_20201123_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bwsmembership',
            old_name='description',
            new_name='Description',
        ),
    ]
