# Generated by Django 3.0.8 on 2020-11-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0009_auto_20201123_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bwsmembership',
            name='Occupation',
            field=models.CharField(choices=[('Working', 'Working'), ('Working student', 'Working student'), ('Student', 'Student')], max_length=200),
        ),
    ]
