# Generated by Django 3.0.8 on 2020-12-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0012_auto_20201130_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=200)),
                ('Organization', models.CharField(max_length=200)),
                ('Cellphone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Reason_donation', models.CharField(choices=[('Fundraising', 'Fundraising'), ('Mentorship program', 'Mentorship program')], max_length=200)),
                ('Amount_donation', models.CharField(choices=[('R500', 'R500'), ('R1000', 'R1000'), ('R1500', 'R1500')], max_length=200)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
