# Generated by Django 3.0.8 on 2020-12-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0015_auto_20201205_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
