# Generated by Django 3.0.8 on 2020-12-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0016_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='BWSfellowship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=200)),
                ('Gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=200)),
                ('Cellphone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Age', models.CharField(choices=[('18-24', '18-24'), ('25-29', '25-29'), ('30-34', '30-34'), ('35-39', '35-39'), ('40-49', '40-49'), ('49 and older', '49 and older')], max_length=200)),
                ('University', models.CharField(max_length=200)),
                ('Race', models.CharField(choices=[('african', 'african'), ('white', 'white'), ('indian', 'indian'), ('color', 'color')], max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Province', models.CharField(choices=[('Eastern Cape', 'Eastern Cape'), ('Free State', 'Free State'), ('Gauteng', 'Gauteng'), ('KwaZulu-Natal', 'KwaZulu-Natal'), ('Limpopo', 'Limpopo'), ('Mpumalanga', 'Mpumalanga'), ('Northern Cape', 'Northern Cape'), ('Western Cape', 'Western Cape'), ('Other', 'Other')], max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('Last_academic_qualification', models.CharField(choices=[('Post PhD', 'Post PhD'), ('PhD', 'PhD'), ('Masters', 'Masters'), ('Honours', 'Honours'), ('Bachelors', 'Bachelors'), ('Diploma', 'Diploma')], max_length=200)),
                ('Current_academic_qualification', models.CharField(choices=[('Post PhD', 'Post PhD'), ('PhD', 'PhD'), ('Masters', 'Masters'), ('Honours', 'Honours'), ('Bachelors', 'Bachelors'), ('Diploma', 'Diploma')], max_length=200)),
                ('Scientific_discipline', models.CharField(max_length=200)),
                ('Subject_major', models.CharField(max_length=200)),
                ('Occupation', models.CharField(choices=[('Working', 'Working'), ('Working student', 'Working student'), ('Student', 'Student')], max_length=200)),
                ('Where_hear_organisation', models.CharField(choices=[('social media', 'Social media'), ('radio', 'Radio'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('university', 'University')], max_length=200)),
                ('Time_to_volunteer', models.CharField(choices=[('up to 2 hrs', 'up to 2 hrs'), ('up to 4 hrs', 'up to 4 hrs'), ('up to 6 hrs', 'up to 6 hrs'), ('1 full day', '1 full day')], max_length=200)),
                ('Conducted_TV_interview', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=200)),
                ('media_handle', models.CharField(default=True, max_length=200)),
                ('Description', models.CharField(max_length=400)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='membership',
        ),
    ]
