# Generated by Django 3.0.8 on 2020-12-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0019_auto_20201214_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='Amount_donation',
            field=models.IntegerField(max_length=200),
        ),
    ]
