# Generated by Django 3.0.8 on 2020-12-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0020_auto_20201214_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='description',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='Amount_donation',
            field=models.IntegerField(),
        ),
    ]
