# Generated by Django 3.0.8 on 2020-12-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0021_auto_20201214_1336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
