# Generated by Django 3.0.8 on 2020-12-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0023_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='description',
        ),
    ]
