# Generated by Django 3.0.8 on 2020-12-17 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0024_remove_videos_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='last_used',
            field=models.DateTimeField(default=datetime.date(2020, 12, 17), editable=False),
        ),
    ]
