# Generated by Django 3.0.8 on 2021-04-17 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0025_eventpost_last_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('scientific_d', models.CharField(max_length=200)),
                ('notifications', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='last_used',
            field=models.DateTimeField(default=datetime.date(2021, 4, 17), editable=False),
        ),
    ]
