# Generated by Django 3.0.8 on 2021-04-17 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0026_auto_20210417_0438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventbus',
            old_name='phone',
            new_name='cellphone',
        ),
        migrations.AddField(
            model_name='eventbus',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
