# Generated by Django 3.0.8 on 2021-04-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0027_auto_20210417_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbus',
            name='business_i',
            field=models.CharField(default=True, max_length=400),
        ),
        migrations.AddField(
            model_name='eventbus',
            name='gain_w',
            field=models.CharField(default=True, max_length=400),
        ),
    ]
