# Generated by Django 3.0.8 on 2021-10-02 18:39

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0028_auto_20210417_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event1Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('degree_level', models.CharField(choices=[('Post PhD', 'Post PhD'), ('PhD', 'PhD'), ('Masters', 'Masters'), ('Honours', 'Honours'), ('Bachelors', 'Bachelors'), ('Diploma', 'Diploma'), ('None', 'None')], max_length=200)),
                ('age', models.CharField(choices=[('18-24', '18-24'), ('25-29', '25-29'), ('30-34', '30-34'), ('35-39', '35-39'), ('40-49', '40-49'), ('49 and older', '49 and older')], max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='EventBus',
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='last_used',
            field=models.DateTimeField(default=datetime.date(2021, 10, 2), editable=False),
        ),
    ]
