# Generated by Django 3.0.8 on 2022-06-01 09:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0030_auto_20220601_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='last_used',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 9, 57, 51, 624064, tzinfo=utc), editable=False),
        ),
    ]
