# Generated by Django 3.0.8 on 2022-06-01 10:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0031_auto_20220601_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='last_used',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 10, 38, 0, 287167, tzinfo=utc), editable=False),
        ),
    ]
