# Generated by Django 3.0.8 on 2022-06-04 06:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0032_auto_20220601_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bwsfellowship',
            name='Where_hear_organisation',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedIn', 'LinkedIn'), ('university', 'University'), ('friend', 'Friend'), ('colleague', 'Colleague ')], max_length=200),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='last_used',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 6, 21, 11, 163030, tzinfo=utc), editable=False),
        ),
    ]
