# Generated by Django 3.0.8 on 2022-07-21 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0038_auto_20220721_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='bwsmembership',
            name='City',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bwsmembership',
            name='Province',
            field=models.CharField(choices=[('Eastern Cape', 'Eastern Cape'), ('Free State', 'Free State'), ('Gauteng', 'Gauteng'), ('KwaZulu-Natal', 'KwaZulu-Natal'), ('Limpopo', 'Limpopo'), ('Mpumalanga', 'Mpumalanga'), ('Northern Cape', 'Northern Cape'), ('Western Cape', 'Western Cape')], max_length=200),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='last_used',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 13, 2, 49, 219059, tzinfo=utc), editable=False),
        ),
    ]
