# Generated by Django 3.0.8 on 2022-07-21 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bwise', '0039_auto_20220721_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bwsmembership',
            name='Country',
            field=models.CharField(choices=[('South Africa', 'South Africa'), ('Outside South Africa', 'Outside South Africa')], max_length=200),
        ),
        migrations.AlterField(
            model_name='eventpost',
            name='last_used',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 13, 21, 8, 39712, tzinfo=utc), editable=False),
        ),
    ]
